import { Raleway } from 'next/font/google'; // Import the Raleway font
import './styles.css'; // Import your global styles

// Configure Raleway font
const raleway = Raleway({
  subsets: ['latin'],
  weight: ['100', '400', '700', '900'], // Specify font weights
  variable: '--font-raleway',
  display: 'swap',
});

export const metadata = {
  title: 'Study Buddy',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Add the Cloudinary Upload Widget script */}
        <script src="https://upload-widget.cloudinary.com/latest/global/all.js" type="text/javascript"></script> 
      </head>
      <body className={`${raleway.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
