import { Raleway } from "next/font/google"; // Import the Raleway font
import "./globals.css";

// Load the Raleway font
const raleway = Raleway({
  variable: "--font-raleway",  // Custom CSS variable for Raleway font
  subsets: ["latin"],         // Language subset
  weight: ["100", "400", "700", "900"], // Specify font weights you want to use
});

export const metadata = {
  title: "Study Buddy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${raleway.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
